name: Update package version
on:
  workflow_dispatch:
    inputs:
      yarn-version-flags:
        description: Flags for yarn version
        default: '--patch'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn version ${{ github.event.inputs.yarn-version-flags }}
    - uses: EndBug/add-and-commit@v7.1.0
